import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../styles/globals.css";
import AuthContextProvider from "@/contexts/AuthContext";
import { SocketIOProvider } from "@/contexts/SocketIOContext";
import SessionProvider from "@/components/SessionProvider";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anima Project - Automatically generated by Anima",
  description: "A Next.js project automatically generated by Anima",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <SessionProvider>
          <AuthContextProvider>
            <SocketIOProvider>
              <main>{children}</main>
            </SocketIOProvider>
          </AuthContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}